// Best-effort mapping from Telegram language_code to IANA timezone
export const LANG_TO_TZ: Record<string, string> = {
  "pt-br": "America/Sao_Paulo",
  pt: "Europe/Lisbon",
  en: "America/New_York",
  "en-us": "America/New_York",
  "en-gb": "Europe/London",
  es: "America/Mexico_City",
  "es-mx": "America/Mexico_City",
  "es-ar": "America/Argentina/Buenos_Aires",
  fr: "Europe/Paris",
  de: "Europe/Berlin",
  it: "Europe/Rome",
  ja: "Asia/Tokyo",
  zh: "Asia/Shanghai",
  "zh-cn": "Asia/Shanghai",
  "zh-tw": "Asia/Taipei",
  ko: "Asia/Seoul",
  ru: "Europe/Moscow",
  ar: "Asia/Riyadh",
  hi: "Asia/Kolkata",
  nl: "Europe/Amsterdam",
  pl: "Europe/Warsaw",
  tr: "Europe/Istanbul",
  sv: "Europe/Stockholm",
  nb: "Europe/Oslo",
  da: "Europe/Copenhagen",
  fi: "Europe/Helsinki",
  uk: "Europe/Kiev",
};
